import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:translator/translator.dart';

class LanguageService extends ChangeNotifier {
  LanguageService._();

  static final LanguageService instance = LanguageService._();
  static const _prefsKey = 'app_language_v1';

  String _currentLanguage = 'hi';
  late SharedPreferences _prefs;
  final GoogleTranslator _translator = GoogleTranslator();

  // Cache for dynamic translations: {'hi': {'Hello': 'नमस्ते'}}
  final Map<String, Map<String, String>> _dynamicCache = {};
  // Set to track pending translations to avoid duplicate requests
  final Set<String> _pendingTranslations = {};

  Future<void> init(SharedPreferences prefs) async {
    _prefs = prefs;
    final saved = prefs.getString(_prefsKey);
    if (saved != null && _strings.containsKey(saved)) {
      _currentLanguage = saved;
    }
  }

  String get currentLanguage => _currentLanguage;

  Future<void> changeLanguage(String code) async {
    if (!_strings.containsKey(code)) return;
    if (_currentLanguage == code) return;
    _currentLanguage = code;
    await _prefs.setString(_prefsKey, code);
    notifyListeners();
  }

  String t(String key) {
    // 1. Check hardcoded strings
    if (_strings[_currentLanguage]?.containsKey(key) ?? false) {
      return _strings[_currentLanguage]![key]!;
    }

    // 2. Check dynamic cache
    if (_dynamicCache[_currentLanguage]?.containsKey(key) ?? false) {
      return _dynamicCache[_currentLanguage]![key]!;
    }

    // 3. Fetch translation dynamically
    _fetchTranslation(key, _currentLanguage);

    // Return original key while loading
    return key;
  }

  Future<void> _fetchTranslation(String text, String targetLang) async {
    final cacheKey = '$targetLang:$text';
    if (_pendingTranslations.contains(cacheKey)) return;

    _pendingTranslations.add(cacheKey);

    try {
      final translation = await _translator.translate(text, to: targetLang);

      if (_dynamicCache[targetLang] == null) {
        _dynamicCache[targetLang] = {};
      }
      _dynamicCache[targetLang]![text] = translation.text;

      // Notify listeners to update UI
      notifyListeners();
    } catch (e) {
      debugPrint('Translation error for "$text" to $targetLang: $e');
    } finally {
      _pendingTranslations.remove(cacheKey);
    }
  }

  static List<Locale> get supportedLocales =>
      _strings.keys.map(Locale.new).toList();

  static const List<Map<String, String>> supportedLanguages = [
    {'code': 'en', 'label': 'English'},
    {'code': 'hi', 'label': 'हिंदी'},
    {'code': 'mr', 'label': 'मराठी'},
    {'code': 'te', 'label': 'తెలుగు'},
    {'code': 'ta', 'label': 'தமிழ்'},
  ];
}

const Map<String, Map<String, String>> _strings = {
  'en': {
    'welcome': 'Welcome to',
    'appName': 'FasalMitra',
    'login': 'Login',
    'register': 'Register',
    'home': 'Home',
    'fullName': 'Full Name',
    'mobile': 'Mobile No.',
    'captcha': 'Captcha',
    'captchaText': 'Captcha Text',
    'sendOtp': 'Send OTP',
    'registerCta': 'Register',
    'newUser': 'New User? Register',
    'alreadyRegistered': 'Already Registered? Login',
    'enterOtp': 'Enter OTP',
    'otpPlaceholder': '••••••',
    'enterPhone': 'Enter Your Phone Number (with Country Code)',
    'otpSentPrefix': 'OTP Sent to',
    'captchaNotReady': 'Captcha Not Ready Yet',
    'captchaEnter': 'Enter Captcha Text',
    'aboutUs': 'About Us',
    'customerCare': 'Customer Care',
    'listProduct': 'List Product',
    'marketplace': 'Marketplace',
    'recentListings': 'Recent Listings',
    'searchByCategory': 'Search by Category',
    'qualityCheck': 'Quality Check / Test Product Quality',
    'searchSeeds': 'Search Seeds / Marketplace',
    'viewAll': 'View All',
    'buyNow': 'Buy Now',
    'qty': 'Qty',
    'processed': 'Processed',
    'unknownFarmer': 'Unknown Farmer',
    'seedPriceMarket': 'Seed Price Market',
    'sellOilseed': 'Sell Oilseed',
    'seedMarket': 'Seed Market',
    'byproductPriceMarket': 'Byproduct Price Market',
    'buyOilseed':
        'Buy Oilseed', // Keeping for backward compat if needed, though unused in grid now
    'myOrders': 'My Orders',

    'searchOilSeed': 'Search Oil Seed',
    'searchPlaceholder': 'Search for seeds, crops...',
    'recentPost': 'Recent Post',
    'menu': 'Menu',
    'usefulWebsites': 'Useful Websites',
    'pmKisan': 'PM Kisan Samman Nidhi',
    'pmFasalBima': 'PM Fasal Bima Yojana',
    'enam': 'e-NAM',
    'soilHealth': 'Soil Health Card',
    'generateCertificate': 'Generate Certificate',
    'krishiSenseTitle': 'KrishiSense : OilSeed Price Prediction AI',
    'hello': 'Hello',
    'trend': 'Trend',
    'rising': 'Rising',
    'falling': 'Falling',
    'sellNow': 'Sell Now',
    'urgentAlertFallback':
        'URGENT: Heavy rainfall expected in Vidarbha region over the next 48 hours. Protect your harvested crops.',
    'soyabean': 'Soyabean',
    'mustard': 'Mustard',
    'sesame': 'Sesame',
    'sunflower': 'Sunflower',
    'groundnut': 'Groundnut',
    'castor': 'Castor',
    'wheat': 'Wheat',
    'rice': 'Rice',
    'corn': 'Corn',
    'cotton': 'Cotton',
    'marketInsights': 'Market Insights',
    'bestSeasonalPick': 'Best Seasonal Pick',
    'riskLevel': 'Risk Level',
    'high': 'High',
    'medium': 'Medium',
    'low': 'Low',
    'expectedProfit': 'Expected Profit',
    'recommendation': 'Recommendation',
    'action': 'Action',
    'reason': 'Reason',
    'seasonalAnalysis': 'Seasonal Analysis',
    'bestMonth': 'Best Month',
    'worstMonth': 'Worst Month',
    'opportunity': 'Opportunity',
    'hold': 'Hold',
    'sell': 'Sell',
    'months': 'Months',
    'urgentAlerts': 'Urgent Alerts',
    'january': 'January',
    'february': 'February',
    'march': 'March',
    'april': 'April',
    'may': 'May',
    'june': 'June',
    'july': 'July',
    'august': 'August',
    'september': 'September',
    'october': 'October',
    'november': 'November',
    'december': 'December',
    'now': 'Now',
    '1m': '1M',
    '3m': '3M',
    '6m': '6M',
  },
  'hi': {
    'welcome': 'आपका स्वागत है',
    'appName': 'फ़सलमित्र',
    'login': 'लॉगिन',
    'register': 'पंजीकरण',
    'home': 'होम',
    'fullName': 'पूरा नाम',
    'mobile': 'मोबाइल नंबर',
    'captcha': 'कैप्चा',
    'captchaText': 'कैप्चा टेक्स्ट',
    'sendOtp': 'ओटीपी भेजें',
    'registerCta': 'पंजीकरण करें',
    'newUser': 'नए उपयोगकर्ता? पंजीकरण करें',
    'alreadyRegistered': 'पहले से पंजीकृत? लॉगिन करें',
    'enterOtp': 'ओटीपी दर्ज करें',
    'otpPlaceholder': '••••••',
    'enterPhone': 'देश कोड सहित मोबाइल नंबर दर्ज करें',
    'otpSentPrefix': 'ओटीपी भेजा गया',
    'captchaNotReady': 'कैप्चा तैयार नहीं है',
    'captchaEnter': 'कैप्चा टेक्स्ट दर्ज करें',
    'aboutUs': 'हमारे बारे में',
    'customerCare': 'ग्राहक सेवा',
    'listProduct': 'उत्पाद सूचीबद्ध करें',
    'marketplace': 'बाज़ार',
    'recentListings': 'हाल की सूचियां',
    'searchByCategory': 'श्रेणी से खोजें',
    'qualityCheck': 'गुणवत्ता जांच / उत्पाद गुणवत्ता परीक्षण',
    'searchSeeds': 'बीज खोजें / बाज़ार',
    'viewAll': 'सभी देखें',
    'buyNow': 'अभी खरीदें',
    'qty': 'मात्रा',
    'processed': 'संसाधित',
    'unknownFarmer': 'अज्ञात किसान',
    'seedPriceMarket': 'बीज मूल्य बाज़ार',
    'sellOilseed': 'तिलहन बेचें',
    'seedMarket': 'बीज बाज़ार',
    'byproductMarket': 'उप-उत्पाद बाज़ार',
    'byproductPriceMarket': 'उप-उत्पाद मूल्य बाज़ार',
    'buyOilseed': 'तिलहन खरीदें',
    'myOrders': 'मेरे ऑर्डर',
    'orderTracking': 'ऑर्डर ट्रैकिंग',
    'searchOilSeed': 'तिलहन खोजें',
    'searchPlaceholder': 'बीज, फसलें खोजें...',
    'recentPost': 'हालिया पोस्ट',
    'menu': 'मेनू',
    'usefulWebsites': 'उपयोगी वेबसाइटें',
    'pmKisan': 'पीएम किसान सम्मान निधि',
    'pmFasalBima': 'पीएम फसल बीमा योजना',
    'enam': 'ई-नाम (e-NAM)',
    'soilHealth': 'मृदा स्वास्थ्य कार्ड',
    'generateCertificate': 'प्रमाणपत्र जनरेट करें',
    'krishiSenseTitle': 'कृषि-सेंस : तिलहन मूल्य भविष्यवाणी एआई',
    'hello': 'नमस्ते',
    'trend': 'प्रवृत्ति',
    'rising': 'बढ़ रहा है',
    'falling': 'गिर रहा है',
    'sellNow': 'अभी बेचें',
    'urgentAlertFallback':
        'अत्यावश्यक: अगले 48 घंटों में विदर्भ क्षेत्र में भारी बारिश की संभावना है। अपनी कटी हुई फसलों को सुरक्षित रखें।',
    'soyabean': 'सोयाबीन',
    'mustard': 'सरसों',
    'sesame': 'तिल',
    'sunflower': 'सूरजमुखी',
    'groundnut': 'मूंगफली',
    'castor': 'अरंडी',
    'wheat': 'गेहूं',
    'rice': 'चावल',
    'corn': 'मक्का',
    'cotton': 'कपास',
    'marketInsights': 'बाज़ार की जानकारी',
    'bestSeasonalPick': 'सर्वोत्तम मौसमी चयन',
    'riskLevel': 'जोखिम स्तर',
    'high': 'उच्च',
    'medium': 'मध्यम',
    'low': 'कम',
    'expectedProfit': 'अपेक्षित लाभ',
    'recommendation': 'सिफारिश',
    'action': 'कार्यवाई',
    'reason': 'कारण',
    'seasonalAnalysis': 'मौसमी विश्लेषण',
    'bestMonth': 'सर्वोत्तम महीना',
    'worstMonth': 'सबसे खराब महीना',
    'opportunity': 'अवसर',
    'hold': 'रोकें',
    'sell': 'बेचें',
    'months': 'महीने',
    'urgentAlerts': 'महत्वपूर्ण अलर्ट',
    'january': 'जनवरी',
    'february': 'फ़रवरी',
    'march': 'मार्च',
    'april': 'अप्रैल',
    'may': 'मई',
    'june': 'जून',
    'july': 'जुलाई',
    'august': 'अगस्त',
    'september': 'सितंबर',
    'october': 'अक्टूबर',
    'november': 'नवंबर',
    'december': 'दिसंबर',
    'now': 'अभी',
    '1m': '1माह',
    '3m': '3माह',
    '6m': '6माह',
  },
  'mr': {
    'welcome': 'आपला स्वागत आहे',
    'appName': 'फसलमित्र',
    'login': 'लॉगिन',
    'register': 'नोंदणी',
    'home': 'मुख्यपृष्ठ',
    'fullName': 'संपूर्ण नाव',
    'mobile': 'मोबाइल क्रमांक',
    'captcha': 'कॅप्चा',
    'captchaText': 'कॅप्चा मजकूर',
    'sendOtp': 'ओटीपी पाठवा',
    'registerCta': 'नोंदणी करा',
    'newUser': 'नवीन वापरकर्ता? नोंदणी करा',
    'alreadyRegistered': 'आधीच नोंदणी केली? लॉगिन करा',
    'enterOtp': 'ओटीपी प्रविष्ट करा',
    'otpPlaceholder': '••••••',
    'enterPhone': 'कृपया देशकोडसह मोबाईल क्रमांक लिहा',
    'otpSentPrefix': 'ओटीपी पाठवला',
    'captchaNotReady': 'कॅप्चा तयार नाही',
    'captchaEnter': 'कॅप्चा मजकूर लिहा',
    'aboutUs': 'आमच्याबद्दल',
    'customerCare': 'ग्राहक सेवा',
    'listProduct': 'उत्पाद सूचीबद्ध करा',
    'marketplace': 'बाजार',
    'recentListings': 'अलीकडील सूची',
    'searchByCategory': 'श्रेणीनुसार शोधा',
    'qualityCheck': 'गुणवत्ता तपासणी / उत्पाद गुणवत्ता चाचणी',
    'searchSeeds': 'बीज शोधा / बाजार',
    'viewAll': 'सर्व पहा',
    'buyNow': 'आता खरेदी करा',
    'qty': 'प्रमाण',
    'processed': 'प्रक्रिया केलेले',
    'unknownFarmer': 'अज्ञात शेतकरी',
    'seedPriceMarket': 'बियाणे दर बाजार',
    'sellOilseed': 'गळीत धान्य विक्री',
    'seedMarket': 'बियाणे बाजार',
    'byproductMarket': 'उप-उत्पादन बाजार',
    'byproductPriceMarket': 'उप-उत्पादन किंमत बाजार',
    'buyOilseed': 'गळीत धान्य खरेदी',
    'myOrders': 'माझ्या ऑर्डर',
    'orderTracking': 'ऑर्डर ट्रॅकिंग',
    'searchOilSeed': 'गळीत धान्य शोधा',
    'searchPlaceholder': 'बियाणे, पिके शोधा...',
    'recentPost': 'अलीकडील पोस्ट',
    'menu': 'मेनू',
    'usefulWebsites': 'उपयोगी वेबसाइट',
    'pmKisan': 'पीएम किसान सन्मान निधी',
    'pmFasalBima': 'पीएम पीक विमा योजना',
    'enam': 'ई-नाम (e-NAM)',
    'soilHealth': 'मृदा आरोग्य पत्रिका',
    'generateCertificate': 'प्रमाणपत्र तयार करा',
    'krishiSenseTitle': 'कृषि-सेंस : गळीत धान्य किंमत अंदाज एआय',
    'hello': 'नमस्कार',
    'trend': 'कल',
    'rising': 'वाढत आहे',
    'falling': 'घटत आहे',
    'sellNow': 'आता विक्री करा',
    'urgentAlertFallback':
        'तातडीचे: पुढील ४८ तासांत विदर्भ भागात मुसळधार पावसाची शक्यता आहे. कापणी केलेल्या पिकांचे संरक्षण करा.',
    'soyabean': 'सोयाबीन',
    'mustard': 'मोहरी',
    'sesame': 'तीळ',
    'sunflower': 'सूर्यफूल',
    'groundnut': 'भुईमूग',
    'castor': 'एरंडेल',
    'wheat': 'गहू',
    'rice': 'तांदूळ',
    'corn': 'मका',
    'cotton': 'कापूस',
    'marketInsights': 'बाजार अंतर्दृष्टी',
    'bestSeasonalPick': 'सर्वोत्तम हंगामी निवड',
    'riskLevel': 'जोखिम पातळी',
    'high': 'उच्च',
    'medium': 'मध्यम',
    'low': 'कमी',
    'expectedProfit': 'अपेक्षित नफा',
    'recommendation': 'शिफारस',
    'action': 'कृती',
    'reason': 'कारण',
    'seasonalAnalysis': 'हंगामी विश्लेषण',
    'bestMonth': 'इष्टतम महिना',
    'worstMonth': 'सर्वात वाईट महिना',
    'opportunity': 'संधी',
    'hold': 'ठेवा',
    'sell': 'विक्री करा',
    'months': 'महिने',
    'urgentAlerts': 'तात्काळ सूचना',
    'january': 'जानेवारी',
    'february': 'फेब्रुवारी',
    'march': 'मार्च',
    'april': 'एप्रिल',
    'may': 'मे',
    'june': 'जून',
    'july': 'जुलै',
    'august': 'ऑगस्ट',
    'september': 'सप्टेंबर',
    'october': 'ऑक्टोबर',
    'november': 'नोव्हेंबर',
    'december': 'डिसेंबर',
    'now': 'आता',
    '1m': '१महिना',
    '3m': '३महिने',
    '6m': '६महिने',
  },
  'te': {
    'welcome': 'స్వాగతం',
    'appName': 'ఫసల్మిత్ర',
    'login': 'లాగిన్',
    'register': 'నమోదు',
    'home': 'హోమ్',
    'fullName': 'పూర్తి పేరు',
    'mobile': 'మొబైల్ నం.',
    'captcha': 'క్యాప్చా',
    'captchaText': 'క్యాప్చా టెక్స్ట్',
    'sendOtp': 'ఓటీపీ పంపు',
    'registerCta': 'నమోదు చేయండి',
    'newUser': 'కొత్త వినియోగదారు? నమోదు',
    'alreadyRegistered': 'ఇప్పటికే నమోదయ్యారా? లాగిన్',
    'enterOtp': 'ఓటీపీ నమోదు చేయండి',
    'otpPlaceholder': '••••••',
    'enterPhone': 'దేశ కోడ్‌తో ఫోన్ నంబర్ ఇవ్వండి',
    'otpSentPrefix': 'ఓటీపీ పంపబడింది',
    'captchaNotReady': 'క్యాప్చా సిద్ధంగా లేదు',
    'captchaEnter': 'క్యాప్చా టెక్స్ట్ నమోదు చేయండి',
    'aboutUs': 'మా గురించి',
    'customerCare': 'కస్టమర్ కేర్',
    'listProduct': 'ఉత్పత్తిని జాబితా చేయండి',
    'marketplace': 'మార్కెట్',
    'recentListings': 'ఇటీవలి జాబితాలు',
    'searchByCategory': 'వర్గం ద్వారా శోధించండి',
    'qualityCheck': 'నాణ్యత తనిఖీ / ఉత్పత్తి నాణ్యత పరీక్ష',
    'searchSeeds': 'విత్తనాలు శోధించండి / మార్కెట్',
    'viewAll': 'అన్నీ చూడండి',
    'buyNow': 'ఇప్పుడే కొనండి',
    'qty': 'పరిమాణం',
    'processed': 'ప్రాసెస్ చేయబడింది',
    'unknownFarmer': 'తెలియని రైతు',
    'seedPriceMarket': 'విత్తన ధర మార్కెట్',
    'sellOilseed': 'నూనె గింజలు అమ్మండి',
    'seedMarket': 'విత్తన మార్కెట్',
    'byproductMarket': 'ఉప ఉత్పత్తి మార్కెట్',
    'byproductPriceMarket': 'ఉప ఉత్పత్తి ధర మార్కెట్',
    'buyOilseed': 'నూనె గింజలు కొనండి',
    'myOrders': 'నా ఆర్డర్లు',
    'orderTracking': 'ఆర్డర్ ట్రాకింగ్',
    'searchOilSeed': 'నూనె గింజలను శోధించండి',
    'searchPlaceholder': 'విత్తనాలు, పంటల కోసం వెతకండి...',
    'recentPost': 'ఇటీవలి పోస్ట్',
    'menu': 'మెనూ',
    'usefulWebsites': 'ఉపయోగకరమైన వెబ్‌సైట్‌లు',
    'pmKisan': 'పిఎం కిసాన్ సమ్మాన్ నిధి',
    'pmFasalBima': 'పిఎం ఫసల్ బీమా యోజన',
    'enam': 'e-NAM',
    'soilHealth': 'సాయిల్ హెల్త్ కార్డ్',
    'generateCertificate': 'సర్టిఫికెట్ రూపొందించండి',
    'krishiSenseTitle': 'కృషి-సెన్స్ : నూనె గింజల ధర అంచనా AI',
    'hello': 'నమస్కారం',
    'trend': 'ధోరణి',
    'rising': 'పెరుగుతోంది',
    'falling': 'పడిపోతోంది',
    'sellNow': 'ఇప్పుడే అమ్మండి',
    'urgentAlertFallback':
        'అత్యవసరం: రాబోయే 48 గంటల్లో విదర్భ ప్రాంతంలో భారీ వర్షాలు కురిసే అవకాశం ఉంది. మీ పంటను రక్షించుకోండి.',
    'soyabean': 'సోయాబీన్',
    'mustard': 'ఆవాలు',
    'sesame': 'నువ్వులు',
    'sunflower': 'ప్రొద్దుతిరుగుడు',
    'groundnut': 'వేరుశెనగ',
    'castor': 'ఆముదము',
    'wheat': 'గోధుమ',
    'rice': 'బియ్యం',
    'corn': 'మక్కజొన్న',
    'cotton': 'పత్తి',
    'marketInsights': 'మార్కెట్ అంతర్దృష్టులు',
    'bestSeasonalPick': 'ఉత్తమ కాలానుగుణ ఎంపిక',
    'riskLevel': 'ప్రమాద స్థాయి',
    'high': 'అధిక',
    'medium': 'మధ్యస్థం',
    'low': 'తక్కువ',
    'expectedProfit': 'ఆశించిన లాభం',
    'recommendation': 'సిఫార్సు',
    'action': 'చర్య',
    'reason': 'కారణం',
    'seasonalAnalysis': 'కాలానుగుణ విశ్లేషణ',
    'bestMonth': 'ఉత్తమ నెల',
    'worstMonth': 'చెత్త నెల',
    'opportunity': 'అవకాశం',
    'hold': 'ఉంచండి',
    'sell': 'అమ్మండి',
    'months': 'నెలలు',
    'urgentAlerts': 'అత్యవసర హెచ్చరికలు',
    'january': 'జనవరి',
    'february': 'ఫిబ్రవరి',
    'march': 'మార్చి',
    'april': 'ఏప్రిల్',
    'may': 'మే',
    'june': 'జూన్',
    'july': 'జూలై',
    'august': 'ఆగస్టు',
    'september': 'సెప్టెంబర్',
    'october': 'అక్టోబర్',
    'november': 'నవంబర్',
    'december': 'డిసెంబర్',
    'now': 'ఇప్పుడు',
    '1m': '1నెల',
    '3m': '3నెలలు',
    '6m': '6నెలలు',
  },
  'ta': {
    'welcome': 'வரவேற்பு',
    'appName': 'பசல்மித்ரா',
    'login': 'உள்நுழைவு',
    'register': 'பதிவு',
    'home': 'முகப்பு',
    'fullName': 'முழு பெயர்',
    'mobile': 'கைபேசி எண்',
    'captcha': 'கேப்சா',
    'captchaText': 'கேப்சா உரை',
    'sendOtp': 'OTP அனுப்பு',
    'registerCta': 'பதிவு செய்யவும்',
    'newUser': 'புதிய பயனர்? பதிவு',
    'alreadyRegistered': 'ஏற்கனவே பதிவுசெய்தீர்களா? உள்நுழைக',
    'enterOtp': 'OTP ஐ உள்ளிடவும்',
    'otpPlaceholder': '••••••',
    'enterPhone': 'நாட்டு குறியுடன் கைபேசி எண்ணை உள்ளிடவும்',
    'otpSentPrefix': 'OTP அனுப்பப்பட்டது',
    'captchaNotReady': 'கேப்சா தயார் இல்லை',
    'captchaEnter': 'கேப்சா உரை உள்ளிடவும்',
    'aboutUs': 'எங்களைப் பற்றி',
    'customerCare': 'வாடிக்கையாளர் பராமரிப்பு',
    'listProduct': 'தயாரிப்பை பட்டியலிடு',
    'marketplace': 'சந்தை',
    'recentListings': 'சமீபத்திய பட்டியல்கள்',
    'searchByCategory': 'வகையால் தேடு',
    'qualityCheck': 'தர சோதனை / தயாரிப்பு தரம் சோதனை',
    'searchSeeds': 'விதைகளைத் தேடு / சந்தை',
    'viewAll': 'அனைத்தையும் பார்க்க',
    'buyNow': 'இப்போது வாங்கவும்',
    'qty': 'அளவு',
    'processed': 'செயலாக்கப்பட்டது',
    'unknownFarmer': 'தெரியாத விவசாயி',
    'seedPriceMarket': 'விதை விலை சந்தை',
    'sellOilseed': 'எண்ணெய் வித்து விற்க',
    'seedMarket': 'விதை சந்தை',
    'byproductMarket': 'துணை தயாரிப்பு சந்தை',
    'byproductPriceMarket': 'துணை தயாரிப்பு விலை சந்தை',
    'buyOilseed': 'எண்ணெய் வித்து வாங்க',
    'myOrders': 'எனது ஆர்டர்கள்',
    'orderTracking': 'ஆர்டர் கண்காணிப்பு',
    'searchOilSeed': 'எண்ணெய் வித்து தேடுக',
    'searchPlaceholder': 'விதைகள், பயிர்களைத் தேடுங்கள்...',
    'recentPost': 'சமீபத்திய இடுகை',
    'menu': 'பட்டியல்',
    'usefulWebsites': 'பயனுள்ள இணையதளங்கள்',
    'pmKisan': 'பிஎம் கிசான் சம்மன் நிதி',
    'pmFasalBima': 'பிஎம் பயிர் காப்பீட்டுத் திட்டம்',
    'enam': 'e-NAM',
    'soilHealth': 'மண் சுகாதார அட்டை',
    'generateCertificate': 'சான்றிதழை உருவாக்கவும்',
    'krishiSenseTitle': 'கிருஷி சென்ஸ் : எண்ணெய் வித்து விலை முன்னறிவிப்பு AI',
    'hello': 'வணக்கம்',
    'trend': 'போக்கு',
    'rising': 'உயர்கிறது',
    'falling': 'வீழ்ச்சியடைகிறது',
    'sellNow': 'இப்போது விற்கவும்',
    'urgentAlertFallback':
        'அவசரம்: அடுத்த 48 மணி நேரத்தில் விதர்பா பகுதியில் கனமழை பெய்ய வாய்ப்புள்ளது. உங்கள் அறுவடை பயிர்களை பாதுகாக்கவும்.',
    'soyabean': 'சோயாபீன்',
    'mustard': 'கடுகு',
    'sesame': 'எள்',
    'sunflower': 'சூரியகாந்தி',
    'groundnut': 'நிலக்கடலை',
    'castor': 'ஆமணக்கு',
    'wheat': 'கோதுமை',
    'rice': 'அரிசி',
    'corn': 'சோளம்',
    'cotton': 'பருத்தி',
    'marketInsights': 'சந்தை நுண்ணறிவு',
    'bestSeasonalPick': 'சிறந்த பருவகால தேர்வு',
    'riskLevel': 'ஆபத்து நிலை',
    'high': 'உயர்',
    'medium': 'நடுத்தர',
    'low': 'குறைந்த',
    'expectedProfit': 'எதிர்பார்க்கப்படும் லாபம்',
    'recommendation': 'பரிந்துரை',
    'action': 'செயல்',
    'reason': 'காரணம்',
    'seasonalAnalysis': 'பருவகால பகுப்பாய்வு',
    'bestMonth': 'சிறந்த மாதம்',
    'worstMonth': 'மோசமான மாதம்',
    'opportunity': 'வாய்ப்பு',
    'hold': 'பிடித்து வைக்கவும்',
    'sell': 'விற்கவும்',
    'months': 'மாதங்கள்',
    'urgentAlerts': 'அவசர எச்சரிக்கைகள்',
    'january': 'ஜனவரி',
    'february': 'பிப்ரவரி',
    'march': 'மார்ச்',
    'april': 'ஏப்ரல்',
    'may': 'மே',
    'june': 'ஜூன்',
    'july': 'ஜூலை',
    'august': 'ஆகஸ்ட்',
    'september': 'செப்டம்பர்',
    'october': 'அக்டோபர்',
    'november': 'நவம்பர்',
    'december': 'டிசம்பர்',
    'now': 'இப்போது',
    '1m': '1மாதம்',
    '3m': '3மாதம்',
    '6m': '6மாதம்',
  },
};
