import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:translator/translator.dart';

class LanguageService extends ChangeNotifier {
  LanguageService._();

  static final LanguageService instance = LanguageService._();
  static const _prefsKey = 'app_language_v1';

  String _currentLanguage = 'hi';
  late SharedPreferences _prefs;
  final GoogleTranslator _translator = GoogleTranslator();

  // Cache for dynamic translations: {'hi': {'Hello': 'नमस्ते'}}
  final Map<String, Map<String, String>> _dynamicCache = {};
  // Set to track pending translations to avoid duplicate requests
  final Set<String> _pendingTranslations = {};

  Future<void> init(SharedPreferences prefs) async {
    _prefs = prefs;
    final saved = prefs.getString(_prefsKey);
    if (saved != null && _strings.containsKey(saved)) {
      _currentLanguage = saved;
    }
  }

  String get currentLanguage => _currentLanguage;

  Future<void> changeLanguage(String code) async {
    // if (!_strings.containsKey(code)) return; // Allow dynamic languages
    if (_currentLanguage == code) return;
    _currentLanguage = code;
    await _prefs.setString(_prefsKey, code);
    notifyListeners();
  }

  String t(String key) {
    // 1. Check hardcoded strings
    if (_strings[_currentLanguage]?.containsKey(key) ?? false) {
      return _strings[_currentLanguage]![key]!;
    }

    // 2. Check dynamic cache
    if (_dynamicCache[_currentLanguage]?.containsKey(key) ?? false) {
      return _dynamicCache[_currentLanguage]![key]!;
    }

    // 3. Fetch translation dynamically
    _fetchTranslation(key, _currentLanguage);

    // Return original key while loading (or english fallback if available elsewhere)
    // Here we return key, but maybe we should return English value if available?
    // Let's return the key for now as keys are often English-ish.
    return _strings['en']?[key] ?? key;
  }

  Future<void> _fetchTranslation(String text, String targetLang) async {
    // If text is a key, look up English text to translate
    String textToTranslate = text;
    if (_strings['en']?.containsKey(text) ?? false) {
      textToTranslate = _strings['en']![text]!;
    }

    final cacheKey = '$targetLang:$text';
    if (_pendingTranslations.contains(cacheKey)) return;

    _pendingTranslations.add(cacheKey);

    try {
      final translation = await _translator.translate(
        textToTranslate,
        to: targetLang,
      );

      if (_dynamicCache[targetLang] == null) {
        _dynamicCache[targetLang] = {};
      }
      _dynamicCache[targetLang]![text] = translation.text;

      // Notify listeners to update UI
      notifyListeners();
    } catch (e) {
      debugPrint('Translation error for "$text" to $targetLang: $e');
    } finally {
      _pendingTranslations.remove(cacheKey);
    }
  }

  static List<Locale> get supportedLocales =>
      supportedLanguages.map((e) => Locale(e['code']!)).toList();

  static const List<Map<String, String>> supportedLanguages = [
    {'code': 'en', 'label': 'English'},
    {'code': 'hi', 'label': 'हिंदी'},
    {'code': 'mr', 'label': 'मराठी'},
    {'code': 'te', 'label': 'తెలుగు'},
    {'code': 'ta', 'label': 'தமிழ்'},
    {'code': 'gu', 'label': 'ગુજરાતી'}, // Gujarati
    {'code': 'bn', 'label': 'বাংলা'}, // Bengali
    {'code': 'kn', 'label': 'కన్నడ'}, // Kannada
    {'code': 'ml', 'label': 'മലയാളം'}, // Malayalam
    {'code': 'or', 'label': 'ଓଡ଼ିଆ'}, // Odia
    {'code': 'pa', 'label': 'ਪੰਜਾਬੀ'}, // Punjabi
    {'code': 'as', 'label': 'অসমীয়া'}, // Assamese
    {'code': 'ur', 'label': 'اردو'}, // Urdu
  ];
}

const Map<String, Map<String, String>> _strings = {
  'en': {
    'welcome': 'Welcome to',
    'appName': 'FasalMitra',
    'login': 'Login',
    'register': 'Register',
    'home': 'Home',
    'fullName': 'Full Name',
    'mobile': 'Mobile No.',
    'captcha': 'Captcha',
    'captchaText': 'Captcha Text',
    'sendOtp': 'Send OTP',
    'registerCta': 'Register',
    'newUser': 'New User? Register',
    'alreadyRegistered': 'Already Registered? Login',
    'enterOtp': 'Enter OTP',
    'otpPlaceholder': '••••••',
    'enterPhone': 'Enter Your Phone Number (with Country Code)',
    'otpSentPrefix': 'OTP Sent to',
    'captchaNotReady': 'Captcha Not Ready Yet',
    'captchaEnter': 'Enter Captcha Text',
    'aboutUs': 'About Us',
    'customerCare': 'Customer Care',
    'listProduct': 'List Product',
    'marketplace': 'Marketplace',
    'recentListings': 'Recent Listings',
    'searchByCategory': 'Search by Category',
    'qualityCheck': 'Quality Check / Test Product Quality',
    'searchSeeds': 'Search Seeds / Marketplace',
    'viewAll': 'View All',
    'buyNow': 'Buy Now',
    'qty': 'Qty',
    'processed': 'Processed',
    'unknownFarmer': 'Unknown Farmer',
    'seedPriceMarket': 'Seed Price Market',
    'sellOilseed': 'Sell Oilseed',
    'seedMarket': 'Seed Market',
    'byproductPriceMarket': 'Byproduct Price Market',
    'buyOilseed':
        'Buy Oilseed', // Keeping for backward compat if needed, though unused in grid now
    'myOrders': 'My Orders',

    'searchOilSeed': 'Search Oil Seed',
    'searchPlaceholder': 'Search for seeds, crops...',
    'recentPost': 'Recent Post',
    'menu': 'Menu',
    'usefulWebsites': 'Useful Websites',
    'pmKisan': 'PM Kisan Samman Nidhi',
    'pmFasalBima': 'PM Fasal Bima Yojana',
    'enam': 'e-NAM',
    'soilHealth': 'Soil Health Card',
    'generateCertificate': 'Generate Certificate',
    'myAccount': 'My Account',
    'ordersReceived': 'Orders Received',
    'myCart': 'My Cart',
    'cartEmpty': 'Your cart is empty',
    'total': 'Total',
    'checkout': 'Checkout',
    'date': 'Date',
    'filterByDate': 'Filter by Date',
    'sortBy': 'Sort by',
    'closest': 'Distance: Closest',
    'priceLow': 'Price: Low to High',
    'priceHigh': 'Price: High to Low',
    'recentlyListed': 'Recently Listed',
    'krishiSenseTitle': 'KrishiSense : OilSeed Price Prediction AI',
    'hello': 'Hello',
    'trend': 'Trend',
    'rising': 'Rising',
    'falling': 'Falling',
    'sellNow': 'Sell Now',
    'urgentAlertFallback':
        'URGENT: Heavy rainfall expected in Vidarbha region over the next 48 hours. Protect your harvested crops.',
    'soyabean': 'Soyabean',
    'mustard': 'Mustard',
    'sesame': 'Sesame',
    'sunflower': 'Sunflower',
    'groundnut': 'Groundnut',
    'castor': 'Castor',
    'wheat': 'Wheat',
    'rice': 'Rice',
    'corn': 'Corn',
    'cotton': 'Cotton',
    'marketInsights': 'Market Insights',
    'bestSeasonalPick': 'Best Seasonal Pick',
    'riskLevel': 'Risk Level',
    'high': 'High',
    'medium': 'Medium',
    'low': 'Low',
    'expectedProfit': 'Expected Profit',
    'recommendation': 'Recommendation',
    'action': 'Action',
    'reason': 'Reason',
    'seasonalAnalysis': 'Seasonal Analysis',
    'bestMonth': 'Best Month',
    'worstMonth': 'Worst Month',
    'opportunity': 'Opportunity',
    'hold': 'Hold',
    'sell': 'Sell',
    'months': 'Months',
    'urgentAlerts': 'Urgent Alerts',
    'january': 'January',
    'february': 'February',
    'march': 'March',
    'april': 'April',
    'may': 'May',
    'june': 'June',
    'july': 'July',
    'august': 'August',
    'september': 'September',
    'october': 'October',
    'november': 'November',
    'december': 'December',
    'now': 'Now',
    '1m': '1M',
    '3m': '3M',
    '6m': '6M',
    'chatIntro': 'Hello! I am KrishiMitra. How can I help you today?',
    'learn': 'Learn',
    'blogPosts': 'Blog Posts',
    'tutorialVideos': 'Tutorial Videos',
    'watchNow': 'Watch Now',
    'readMore': 'Read More',
    // Create Listing Keys
    'categoryLabel': 'Category',
    'productNameLabel': 'Product Name',
    'productNameHint': 'Type to search...',
    'dateLabel': 'Processing Date',
    'qtyLabel': 'Quantity (kg)',
    'priceLabel': 'Price per kg (INR)',
    'certLabel': 'Certificate (PDF/JPG)',
    'chooseFile': 'Choose File',
    'noFile': 'No file chosen',
    'imageLabel': 'Product Image',
    'locationLabel': 'State / Location',
    'submitListing': 'Create Listing',
    'seeds': 'Seeds',
    'byproduct': 'Byproduct',
    // Product Card
    'farmer': 'Farmer',
    'available': 'Available',
    'score': 'Score',
    'viewCert': 'View Certificate',
    'loginToPurchase': 'Please Login to Purchase',
    'addedToCart': 'added to cart',
    'price': 'Price',
    'loc': 'Loc',
    // Home Alerts
    'pleaseLoginList': 'Please login to list a product',
    'pleaseLoginMarket': 'Please login to access Marketplace',
    'pleaseLoginPrice': 'Please login to view prices',
    'pleaseLogin': 'Please login first',
    'aboutUsSoon': 'About Us coming soon',
    'customerCareSoon': 'Customer Care coming soon',
    'pleaseLoginCert': 'Please login to generate certificate',
    'askAi': 'Ask KrishiMitra AI',
    // Marketplace
    'byproductMarket': 'Byproduct Market',
    'noListings': 'No listings found',
    'error': 'Error',
    'viewing': 'Viewing',
    // Certificate
    'genCertTitle': 'Generate Quality Certificate',
    'commodityLabel': 'Commodity',
    'commodityHint': 'e.g. Wheat, Rice, Mustard',
    'enterCommodity': 'Please enter commodity name',
    'processingDate': 'Processing Date',
    'selectDate': 'Please select a date',
    'generateCertBtn': 'GENERATE CERTIFICATE',
    'certGenerated': 'Certificate Generated Successfully!',
    'somethingWrong': 'Something went wrong',
    'certReady': 'Certificate Ready!',
    'downloadCert': 'Download Certificate',
    // Chat
    'chatInputHint': 'Ask about farming...',
    // Auth
    'emailLabel': 'Email',
    'mobileLabel': 'Phone No.',
    'passwordLabel': 'Password',
    'usernameLabel': 'Username',
    'stateLabel': 'State',
    'emailRequired': 'Email is required',
    'emailInvalid': 'Enter a valid email',
    'passwordRequired': 'Password is required',
    'passwordLength': 'Password must be at least 6 characters',
    'usernameRequired': 'Username is required',
    'mobileRequired': 'Mobile number is required',
    'mobileInvalid': 'Enter a valid mobile number',
    'stateRequired': 'State is required',
    'registerSuccess': 'Registration successful!',
    // Cart/Orders/Profile
    'clearCart': 'Clear Cart',
    'orderSuccess': 'Order placed successfully!',
    'orderFailed': 'Order failed',
    'noOrders': 'No orders found',
    'retry': 'Retry',
    'forYourListings': 'For your listings',
    'logout': 'Logout',
    'unknownUser': 'Unknown User',
    'view': 'View',
    // Profile & Orders
    'userProfile': 'User Profile',
    'tokenBalance': 'Token Balance',
    'authRequired': 'Authentication Required',
    'loginToViewProfile': 'Please login to view your profile.',
    'orderNumber': 'Order #',
    'productLabel': 'Product',
    'amountLabel': 'Amount',
    'statusLabel': 'Status',
    'receiptConfirmed': 'Receipt Confirmed',
    'refundRequested': 'Refund Requested',
    'receivedGood': 'Received\nGood',
    'notReceived': 'Not\nReceived',
    'statusDeposited': 'DEPOSITED',
    'statusCompleted': 'COMPLETED',
  },
  'hi': {
    'welcome': 'आपका स्वागत है',
    'appName': 'फ़सलमित्र',
    'login': 'लॉगिन करें',
    'register': 'खाता बनाएं',
    'home': 'होम',
    'fullName': 'पूरा नाम',
    'mobile': 'मोबाइल नंबर',
    'captcha': 'कैप्चा',
    'captchaText': 'कैप्चा टेक्स्ट',
    'sendOtp': 'ओटीपी भेजें',
    'registerCta': 'खाता बनाएं',
    'newUser': 'नए उपयोगकर्ता? खाता बनाएं',
    'alreadyRegistered': 'पहले से पंजीकृत? लॉगिन करें',
    'enterOtp': 'ओटीपी दर्ज करें',
    'otpPlaceholder': '••••••',
    'enterPhone': 'देश कोड सहित मोबाइल नंबर दर्ज करें',
    'otpSentPrefix': 'ओटीपी भेजा गया',
    'captchaNotReady': 'कैप्चा तैयार नहीं है',
    'captchaEnter': 'कैप्चा टेक्स्ट दर्ज करें',
    'aboutUs': 'हमारे बारे में',
    'customerCare': 'ग्राहक सेवा',
    'listProduct': 'सामान बेचें',
    'marketplace': 'बाज़ार',
    'recentListings': 'नई लिस्टिंग',
    'searchByCategory': 'श्रेणी से खोजें',
    'qualityCheck': 'माल की जांच',
    'searchSeeds': 'बीज ढूँढें',
    'viewAll': 'सभी देखें',
    'buyNow': 'अभी खरीदें',
    'qty': 'मात्रा',
    'processed': 'प्रोसेस्ड',
    'unknownFarmer': 'अज्ञात किसान',
    'seedPriceMarket': 'बीज के भाव',
    'sellOilseed': 'तिलहन बेचें',
    'seedMarket': 'बीज बाज़ार',

    'byproductPriceMarket': 'खली / अन्य के भाव',
    'buyOilseed': 'तिलहन खरीदें',
    'myOrders': 'मेरे ऑर्डर',
    'orderTracking': 'ऑर्डर ट्रैकिंग',
    'searchOilSeed': 'तिलहन खोजें',

    'recentPost': 'हालिया पोस्ट',
    'menu': 'मेनू',
    'usefulWebsites': 'उपयोगी वेबसाइटें',
    'pmKisan': 'पीएम किसान सम्मान निधि',
    'pmFasalBima': 'पीएम फसल बीमा योजना',
    'enam': 'ई-नाम (e-NAM)',
    'soilHealth': 'मृदा स्वास्थ्य कार्ड',
    'generateCertificate': 'प्रमाणपत्र जनरेट करें',
    'krishiSenseTitle': 'कृषि-सेंस : तिलहन मूल्य भविष्यवाणी एआई',
    'hello': 'नमस्ते',
    'trend': 'प्रवृत्ति',
    'rising': 'बढ़ रहा है',
    'falling': 'गिर रहा है',
    'sellNow': 'अभी बेचें',
    'urgentAlertFallback':
        'अत्यावश्यक: अगले 48 घंटों में विदर्भ क्षेत्र में भारी बारिश की संभावना है। अपनी कटी हुई फसलों को सुरक्षित रखें।',
    'soyabean': 'सोयाबीन',
    'mustard': 'सरसों',
    'sesame': 'तिल',
    'sunflower': 'सूरजमुखी',
    'groundnut': 'मूंगफली',
    'castor': 'अरंडी',
    'wheat': 'गेहूं',
    'rice': 'चावल',
    'corn': 'मक्का',
    'cotton': 'कपास',
    'marketInsights': 'बाज़ार की जानकारी',
    'bestSeasonalPick': 'सर्वोत्तम मौसमी चयन',
    'riskLevel': 'जोखिम स्तर',
    'high': 'उच्च',
    'medium': 'मध्यम',
    'low': 'कम',
    'expectedProfit': 'अपेक्षित लाभ',
    'recommendation': 'सिफारिश',
    'action': 'कार्यवाई',
    'reason': 'कारण',
    'seasonalAnalysis': 'मौसमी विश्लेषण',
    'bestMonth': 'सर्वोत्तम महीना',
    'worstMonth': 'सबसे खराब महीना',
    'opportunity': 'अवसर',
    'hold': 'रोकें',
    'sell': 'बेचें',
    'months': 'महीने',
    'urgentAlerts': 'महत्वपूर्ण अलर्ट',
    'january': 'जनवरी',
    'february': 'फ़रवरी',
    'march': 'मार्च',
    'april': 'अप्रैल',
    'may': 'मई',
    'june': 'जून',
    'july': 'जुलाई',
    'august': 'अगस्त',
    'september': 'सितंबर',
    'october': 'अक्टूबर',
    'november': 'नवंबर',
    'december': 'दिसंबर',
    'now': 'अभी',
    '1m': '1माह',
    '3m': '3माह',
    '6m': '6माह',
    'chatIntro': 'नमस्ते! मैं कृषि मित्र हूँ। मैं आपकी कैसे मदद कर सकता हूँ?',
    'learn': 'सीखें',
    'blogPosts': 'ब्लॉग पोस्ट',
    'tutorialVideos': 'ट्यूटोरियल वीडियो',
    'watchNow': 'अभी देखें',
    'readMore': 'और पढ़ें',
    // Create Listing Keys
    'categoryLabel': 'किस्म / श्रेणी',
    'productNameLabel': 'फसल / सामान का नाम',
    'productNameHint': 'लिखकर खोजें...',
    'dateLabel': 'तारीख',
    'qtyLabel': 'वजन (किलो)',
    'priceLabel': 'भाव (1 किलो का)',
    'certLabel': 'सर्टिफिकेट / कागज',
    'chooseFile': 'फाइल चुनें',
    'noFile': 'कुछ नहीं चुना',
    'imageLabel': 'फसल की फोटो',
    'locationLabel': 'राज्य / जगह',
    'submitListing': 'सामान बेचें',
    'seeds': 'बीज',
    'byproduct': 'खली / अन्य',
    // Product Card
    'farmer': 'किसान',
    'available': 'उपलब्ध',
    'score': 'स्कोर',
    'viewCert': 'सर्टिफिकेट देखें',
    'loginToPurchase': 'खरीदने के लिए लॉगिन करें',
    'addedToCart': 'कार्ट में जोड़ा गया',
    'price': 'भाव',
    'loc': 'जगह',
    // Home Alerts
    'pleaseLoginList': 'सामान बेचने के लिए लॉगिन करें',
    'pleaseLoginMarket': 'बाज़ार देखने के लिए लॉगिन करें',
    'pleaseLoginPrice': 'भाव देखने के लिए लॉगिन करें',
    'pleaseLogin': 'कृपया पहले लॉगिन करें',
    'aboutUsSoon': 'हमारे बारे में - जल्द आ रहा है',
    'customerCareSoon': 'ग्राहक सेवा - जल्द आ रहा है',
    'pleaseLoginCert': 'सर्टिफिकेट के लिए लॉगिन करें',
    'askAi': 'कृषि मित्र से पूछें',
    // Marketplace
    'searchPlaceholder': 'बीज, उत्पाद खोजें...',
    'sortBy': 'क्रम में लगाएं',
    'closest': 'दूरी: सबसे नज़दीक',
    'priceLow': 'भाव: कम से ज़्यादा',
    'priceHigh': 'भाव: ज़्यादा से कम',
    'recentlyListed': 'हाल ही में सूचीबद्ध',
    'filterByDate': 'तारीख से खोजें',
    'noListings': 'कोई लिस्टिंग नहीं मिली',
    'error': 'त्रुटि',
    'viewing': 'देख रहे हैं',
    // Certificate
    'genCertTitle': 'गुणवत्ता प्रमाण पत्र बनाएं',
    'commodityLabel': 'फसल / वस्तु',
    'commodityHint': 'जैसे गेहूं, चावल, सरसों',
    'enterCommodity': 'कृपया फसल का नाम लिखें',
    'processingDate': 'प्रसंस्करण तारीख',
    'selectDate': 'कृपया तारीख चुनें',
    'generateCertBtn': 'प्रमाण पत्र बनाएं',
    'certGenerated': 'प्रमाण पत्र सफलतापूर्वक बन गया!',
    'somethingWrong': 'कुछ गड़बड़ हो गई',
    'certReady': 'प्रमाण पत्र तैयार है!',
    'downloadCert': 'डाउनलोड करें',
    // Chat
    'chatInputHint': 'खेती के बारे में पूछें...',
    // Auth
    'emailLabel': 'ईमेल',
    'mobileLabel': 'मोबाइल नंबर',
    'passwordLabel': 'पासवर्ड',
    'usernameLabel': 'उपयोगकर्ता नाम',
    'stateLabel': 'राज्य',
    'emailRequired': 'ईमेल आवश्यक है',
    'emailInvalid': 'सही ईमेल दर्ज करें',
    'passwordRequired': 'पासवर्ड आवश्यक है',
    'passwordLength': 'पासवर्ड कम से कम 6 अक्षरों का होना चाहिए',
    'usernameRequired': 'नाम आवश्यक है',
    'mobileRequired': 'मोबाइल नंबर आवश्यक है',
    'mobileInvalid': 'सही मोबाइल नंबर दर्ज करें',
    'stateRequired': 'राज्य चुनें',
    'registerSuccess': 'पंजीकरण सफल!',
    // Cart/Orders/Profile
    'clearCart': 'कार्ट खाली करें',
    'orderSuccess': 'ऑर्डर सफलतापूर्वक दिया गया!',
    'orderFailed': 'ऑर्डर विफल',
    'noOrders': 'कोई ऑर्डर नहीं मिला',
    'retry': 'पुनः प्रयास करें',
    'forYourListings': 'आपकी लिस्टिंग के लिए',
    'logout': 'लॉग आउट',
    'unknownUser': 'अज्ञात उपयोगकर्ता',
    'ordersReceived': 'प्राप्त ऑर्डर',
    'view': 'देखें',
    // Profile & Orders
    'userProfile': 'उपयोगकर्ता प्रोफ़ाइल',
    'tokenBalance': 'टोकन बैलेंस',
    'authRequired': 'लॉगिन आवश्यक है',
    'loginToViewProfile': 'कृपया अपना प्रोफ़ाइल देखने के लिए लॉगिन करें।',
    'orderNumber': 'ऑर्डर #',
    'productLabel': 'सामान',
    'amountLabel': 'राशि',
    'statusLabel': 'स्थिति',
    'receiptConfirmed': 'रसीद की पुष्टि की गई',
    'refundRequested': 'रिफंड का अनुरोध किया गया',
    'receivedGood': 'सामान\nप्राप्त हुआ',
    'notReceived': 'प्राप्त\nनहीं हुआ',
    'statusDeposited': 'जमा किया गया',
    'statusCompleted': 'पूर्ण हुआ',
  },
  'mr': {
    'welcome': 'आपला स्वागत आहे',
    'appName': 'फसलमित्र',
    'login': 'लॉगिन',
    'register': 'खाते उघडा',
    'home': 'मुख्य',
    'fullName': 'संपूर्ण नाव',
    'mobile': 'मोबाइल क्रमांक',
    'captcha': 'कॅप्चा',
    'captchaText': 'कॅप्चा मजकूर',
    'sendOtp': 'ओटीपी पाठवा',
    'registerCta': 'नोंदणी करा',
    'newUser': 'नवीन वापरकर्ता? नोंदणी करा',
    'alreadyRegistered': 'आधीच नोंदणी केली? लॉगिन करा',
    'enterOtp': 'ओटीपी प्रविष्ट करा',
    'otpPlaceholder': '••••••',
    'enterPhone': 'कृपया देशकोडसह मोबाईल क्रमांक लिहा',
    'otpSentPrefix': 'ओटीपी पाठवला',
    'captchaNotReady': 'कॅप्चा तयार नाही',
    'captchaEnter': 'कॅप्चा मजकूर लिहा',
    'aboutUs': 'आमच्याबद्दल',
    'customerCare': 'ग्राहक सेवा',
    'listProduct': 'सामान विका',
    'marketplace': 'बाजार',
    'recentListings': 'अलीकडील सूची',
    'searchByCategory': 'श्रेणीनुसार शोधा',
    'qualityCheck': 'माल तपासणी',
    'searchSeeds': 'बियाणे शोधा',
    'viewAll': 'सर्व पहा',
    'buyNow': 'आता खरेदी करा',
    'qty': 'प्रमाण',
    'processed': 'प्रक्रिया केलेले',
    'unknownFarmer': 'अज्ञात शेतकरी',
    'seedPriceMarket': 'बियाणे बाजार भाव',
    'sellOilseed': 'गळीत धान्य विक्री',
    'seedMarket': 'बियाणे बाजार',

    'byproductPriceMarket': 'पेंड / इतर बाजार भाव',
    'buyOilseed': 'गळीत धान्य खरेदी',
    'myOrders': 'माझ्या ऑर्डर',
    'orderTracking': 'ऑर्डर ट्रॅकिंग',
    'searchOilSeed': 'गळीत धान्य शोधा',

    'recentPost': 'अलीकडील पोस्ट',
    'menu': 'मेनू',
    'usefulWebsites': 'उपयोगी वेबसाइट',
    'pmKisan': 'पीएम किसान सन्मान निधी',
    'pmFasalBima': 'पीएम पीक विमा योजना',
    'enam': 'ई-नाम (e-NAM)',
    'soilHealth': 'मृदा आरोग्य पत्रिका',
    'generateCertificate': 'प्रमाणपत्र तयार करा',
    'krishiSenseTitle': 'कृषि-सेंस : गळीत धान्य किंमत अंदाज एआय',
    'hello': 'नमस्कार',
    'trend': 'कल',
    'rising': 'वाढत आहे',
    'falling': 'घटत आहे',
    'sellNow': 'आता विक्री करा',
    'urgentAlertFallback':
        'तातडीचे: पुढील ४८ तासांत विदर्भ भागात मुसळधार पावसाची शक्यता आहे. कापणी केलेल्या पिकांचे संरक्षण करा.',
    'soyabean': 'सोयाबीन',
    'mustard': 'मोहरी',
    'sesame': 'तीळ',
    'sunflower': 'सूर्यफूल',
    'groundnut': 'भुईमूग',
    'castor': 'एरंडेल',
    'wheat': 'गहू',
    'rice': 'तांदूळ',
    'corn': 'मक्का',
    'cotton': 'कापूस',
    'marketInsights': 'बाजार अंतर्दृष्टी',
    'bestSeasonalPick': 'सर्वोत्तम हंगामी निवड',
    'riskLevel': 'जोखिम पातळी',
    'high': 'उच्च',
    'medium': 'मध्यम',
    'low': 'कमी',
    'expectedProfit': 'अपेक्षित नफा',
    'recommendation': 'शिफारस',
    'action': 'कृती',
    'reason': 'कारण',
    'seasonalAnalysis': 'हंगामी विश्लेषण',
    'bestMonth': 'इष्टतम महिना',
    'worstMonth': 'सर्वात वाईट महिना',
    'opportunity': 'संधी',
    'hold': 'ठेवा',
    'sell': 'विक्री करा',
    'months': 'महिने',
    'urgentAlerts': 'तात्काळ सूचना',
    'january': 'जानेवारी',
    'february': 'फेब्रुवारी',
    'march': 'मार्च',
    'april': 'एप्रिल',
    'may': 'मे',
    'june': 'जून',
    'july': 'जुलै',
    'august': 'ऑगस्ट',
    'september': 'सप्टेंबर',
    'october': 'ऑक्टोबर',
    'november': 'नोव्हेंबर',
    'december': 'डिसेंबर',
    'now': 'आता',
    '1m': '१महिना',
    '3m': '३महिने',
    '6m': '६महिने',
    'chatIntro': 'नमस्कार! मी कृषिमित्र आहे. मी तुम्हाला कशी मदत करू शकतो?',
    'learn': 'शिका',
    'blogPosts': 'ब्लॉग पोस्ट',
    'tutorialVideos': 'ट्यूटोरियल व्हिडिओ',
    'watchNow': 'आता पहा',
    'readMore': 'अधिक वाचा',
    // Create Listing Keys
    'categoryLabel': 'प्रकार / श्रेणी',
    'productNameLabel': 'पिकाचे नाव',
    'productNameHint': 'शोधण्यासाठी लिहा...',
    'dateLabel': 'तारीख',
    'qtyLabel': 'वजन (किलो)',
    'priceLabel': 'भाव (प्रति किलो)',
    'certLabel': 'सर्टिफिकेट / कागदपत्रे',
    'chooseFile': 'निवडा',
    'noFile': 'निवडले नाही',
    'imageLabel': 'मालाचा फोटो',
    'locationLabel': 'राज्य / ठिकाण',
    'submitListing': 'विक्रीसाठी टाका',
    'seeds': 'बियाणे',
    'byproduct': 'पेंड / इतर',
    // Product Card
    'farmer': 'शेतकरी',
    'available': 'उपलब्ध',
    'score': 'स्कोर',
    'viewCert': 'सर्टिफिकेट पहा',
    'loginToPurchase': 'खरेदी करण्यासाठी लॉगिन करा',
    'addedToCart': 'कार्टमध्ये जोडले',
    'price': 'भाव',
    'loc': 'ठिकाण',
    // Home Alerts
    'pleaseLoginList': 'सामान विकण्यासाठी लॉगिन करा',
    'pleaseLoginMarket': 'बाजार पाहण्यासाठी लॉगिन करा',
    'pleaseLoginPrice': 'भाव पाहण्यासाठी लॉगिन करा',
    'pleaseLogin': 'कृपया आधी लॉगिन करा',
    'aboutUsSoon': 'आमच्याबद्दल - लवकरच येत आहे',
    'customerCareSoon': 'ग्राहक सेवा - लवकरच येत आहे',
    'pleaseLoginCert': 'प्रमाणपत्रासाठी लॉगिन करा',
    'askAi': 'कृषी मित्राला विचारा',
    // Marketplace
    'searchPlaceholder': 'बियाणे, उत्पाद शोधा...',
    'sortBy': 'क्रमवारी लावा',
    'closest': 'अंतर: सर्वात जवळ',
    'priceLow': 'भाव: कमी ते जास्त',
    'priceHigh': 'भाव: जास्त ते कमी',
    'recentlyListed': 'अलीकडे सूचीबद्ध केलेले',
    'filterByDate': 'तारखेनुसार फिल्टर करा',
    'noListings': 'कोणतीही लिस्टिंग सापडली नाही',
    'error': 'त्रुटी',
    'viewing': 'पाहत आहे',
    // Certificate
    'genCertTitle': 'गुणवत्ता प्रमाणपत्र तयार करा',
    'commodityLabel': 'पीक / वस्तू',
    'commodityHint': 'उदा. गहू, तांदूळ, मोहरी',
    'enterCommodity': 'कृपया पिकाचे नाव लिहा',
    'processingDate': 'प्रक्रिया तारीख',
    'selectDate': 'कृपया तारीख निवडा',
    'generateCertBtn': 'प्रमाणपत्र बनवा',
    'certGenerated': 'प्रमाणपत्र यशस्वीरित्या तयार झाले!',
    'somethingWrong': 'काहीतरी चूक झाली',
    'certReady': 'प्रमाणपत्र तयार आहे!',
    'downloadCert': 'डाउनलोड करा',
    // Chat
    'chatInputHint': 'शेतीबद्दल विचारा...',
    // Auth
    'emailLabel': 'ईमेल',
    'mobileLabel': 'मोबाईल नंबर',
    'passwordLabel': 'पासवर्ड',
    'usernameLabel': 'वापरकर्ता नाव',
    'stateLabel': 'राज्य',
    'emailRequired': 'ईमेल आवश्यक आहे',
    'emailInvalid': 'वैध ईमेल प्रविष्ट करा',
    'passwordRequired': 'पासवर्ड आवश्यक आहे',
    'passwordLength': 'पासवर्ड किमान ६ अक्षरांचा असावा',
    'usernameRequired': 'नाव आवश्यक आहे',
    'mobileRequired': 'मोबाईल नंबर आवश्यक आहे',
    'mobileInvalid': 'वैध मोबाईल नंबर प्रविष्ट करा',
    'stateRequired': 'राज्य निवडा',
    'registerSuccess': 'नोंदणी यशस्वी!',
    // Cart/Orders/Profile
    'clearCart': 'कार्ट रिकामी करा',
    'orderSuccess': 'ऑर्डर यशस्वीरित्या दिली!',
    'orderFailed': 'ऑर्डर अयशस्वी',
    'noOrders': 'कोणतीही ऑर्डर सापडली नाही',
    'retry': 'पुन्हा प्रयत्न करा',
    'forYourListings': 'तुमच्या लिस्टिंगसाठी',
    'logout': 'लॉग आउट',
    'unknownUser': 'अज्ञात वापरकर्ता',
    'ordersReceived': 'प्राप्त ऑर्डर',
    'view': 'पहा',
    // Profile & Orders
    'userProfile': 'वापरकर्ता प्रोफाइल',
    'tokenBalance': 'टोकन बॅलन्स',
    'authRequired': 'लॉगिन आवश्यक आहे',
    'loginToViewProfile': 'कृपया आपली प्रोफाइल पाहण्यासाठी लॉगिन करा.',
    'orderNumber': 'ऑर्डर #',
    'productLabel': 'वस्तू',
    'amountLabel': 'रक्कम',
    'statusLabel': 'स्थिती',
    'receiptConfirmed': 'पावती निश्चित केली',
    'refundRequested': 'परताव्याची विनंती केली',
    'receivedGood': 'सामान\nमिळाले',
    'notReceived': 'प्राप्त नाही\nझाले',
    'statusDeposited': 'जमा केले',
    'statusCompleted': 'पूर्ण झाले',
  },
  'te': {
    'welcome': 'స్వాగతం',
    'appName': 'ఫసల్మిత్ర',
    'login': 'లాగిన్',
    'register': 'నమోదు',
    'home': 'హోమ్',
    'fullName': 'పూర్తి పేరు',
    'mobile': 'మొబైల్ నం.',
    'captcha': 'క్యాప్చా',
    'captchaText': 'క్యాప్చా టెక్స్ట్',
    'sendOtp': 'ఓటీపీ పంపు',
    'registerCta': 'నమోదు చేయండి',
    'newUser': 'కొత్త వినియోగదారు? నమోదు',
    'alreadyRegistered': 'ఇప్పటికే నమోదయ్యారా? లాగిన్',
    'enterOtp': 'ఓటీపీ నమోదు చేయండి',
    'otpPlaceholder': '••••••',
    'enterPhone': 'దేశ కోడ్‌తో ఫోన్ నంబర్ ఇవ్వండి',
    'otpSentPrefix': 'ఓటీపీ పంపబడింది',
    'captchaNotReady': 'క్యాప్చా సిద్ధంగా లేదు',
    'captchaEnter': 'క్యాప్చా టెక్స్ట్ నమోదు చేయండి',
    'aboutUs': 'మా గురించి',
    'customerCare': 'కస్టమర్ కేర్',
    'listProduct': 'ఉత్పత్తిని జాబితా చేయండి',
    'marketplace': 'మార్కెట్',
    'recentListings': 'ఇటీవలి జాబితాలు',
    'searchByCategory': 'వర్గం ద్వారా శోధించండి',
    'qualityCheck': 'నాణ్యత తనిఖీ / ఉత్పత్తి నాణ్యత పరీక్ష',
    'searchSeeds': 'విత్తనాలు శోధించండి / మార్కెట్',
    'viewAll': 'అన్నీ చూడండి',
    'buyNow': 'ఇప్పుడే కొనండి',
    'qty': 'పరిమాణం',
    'processed': 'ప్రాసెస్ చేయబడింది',
    'unknownFarmer': 'తెలియని రైతు',
    'seedPriceMarket': 'విత్తన ధర మార్కెట్',
    'sellOilseed': 'నూనె గింజలు అమ్మండి',
    'seedMarket': 'విత్తన మార్కెట్',
    'byproductMarket': 'ఉప ఉత్పత్తి మార్కెట్',
    'byproductPriceMarket': 'ఉప ఉత్పత్తి ధర మార్కెట్',
    'buyOilseed': 'నూనె గింజలు కొనండి',
    'myOrders': 'నా ఆర్డర్లు',
    'orderTracking': 'ఆర్డర్ ట్రాకింగ్',
    'searchOilSeed': 'నూనె గింజలను శోధించండి',
    'searchPlaceholder': 'విత్తనాలు, పంటల కోసం వెతకండి...',
    'recentPost': 'ఇటీవలి పోస్ట్',
    'menu': 'మెనూ',
    'usefulWebsites': 'ఉపయోగకరమైన వెబ్‌సైట్‌లు',
    'pmKisan': 'పిఎం కిసాన్ సమ్మాన్ నిధి',
    'pmFasalBima': 'పిఎం ఫసల్ బీమా యోజన',
    'enam': 'e-NAM',
    'soilHealth': 'సాయిల్ హెల్త్ కార్డ్',
    'generateCertificate': 'సర్టిఫికెట్ రూపొందించండి',
    'krishiSenseTitle': 'కృషి-సెన్స్ : నూనె గింజల ధర అంచనా AI',
    'hello': 'నమస్కారం',
    'trend': 'ధోరణి',
    'rising': 'పెరుగుతోంది',
    'falling': 'పడిపోతోంది',
    'sellNow': 'ఇప్పుడే అమ్మండి',
    'urgentAlertFallback':
        'అత్యవసరం: రాబోయే 48 గంటల్లో విదర్భ ప్రాంతంలో భారీ వర్షాలు కురిసే అవకాశం ఉంది. మీ పంటను రక్షించుకోండి.',
    'soyabean': 'సోయాబీన్',
    'mustard': 'ఆవాలు',
    'sesame': 'నువ్వులు',
    'sunflower': 'ప్రొద్దుతిరుగుడు',
    'groundnut': 'వేరుశెనగ',
    'castor': 'ఆముదము',
    'wheat': 'గోధుమ',
    'rice': 'బియ్యం',
    'corn': 'మక్కజొన్న',
    'cotton': 'పత్తి',
    'marketInsights': 'మార్కెట్ అంతర్దృష్టులు',
    'bestSeasonalPick': 'ఉత్తమ కాలానుగుణ ఎంపిక',
    'riskLevel': 'ప్రమాద స్థాయి',
    'high': 'అధిక',
    'medium': 'మధ్యస్థం',
    'low': 'తక్కువ',
    'expectedProfit': 'ఆశించిన లాభం',
    'recommendation': 'సిఫార్సు',
    'action': 'చర్య',
    'reason': 'కారణం',
    'seasonalAnalysis': 'కాలానుగుణ విశ్లేషణ',
    'bestMonth': 'ఉత్తమ నెల',
    'worstMonth': 'చెత్త నెల',
    'opportunity': 'అవకాశం',
    'hold': 'ఉంచండి',
    'sell': 'అమ్మండి',
    'months': 'నెలలు',
    'urgentAlerts': 'అత్యవసర హెచ్చరికలు',
    'january': 'జనవరి',
    'february': 'ఫిబ్రవరి',
    'march': 'మార్చి',
    'april': 'ఏప్రిల్',
    'may': 'మే',
    'june': 'జూన్',
    'july': 'జూలై',
    'august': 'ఆగస్టు',
    'september': 'సెప్టెంబర్',
    'october': 'అక్టోబర్',
    'november': 'నవంబర్',
    'december': 'డిసెంబర్',
    'now': 'ఇప్పుడు',
    '1m': '1నెల',
    '3m': '3నెలలు',
    '6m': '6నెలలు',
    'chatIntro': 'నమస్కారం! నేను కృషిమిత్రాను. నేను మీకు ఎలా సహాయపడగలను?',
    'learn': 'నేర్చుకోండి',
    'blogPosts': 'బ్లాగ్ పోస్ట్‌లు',
    'tutorialVideos': 'ట్యుటోరియల్ వీడియోలు',
    'watchNow': 'ఇప్పుడే చూడండి',
    'readMore': 'మరింత చదవండి',
  },
  'ta': {
    'welcome': 'வரவேற்பு',
    'appName': 'பசல்மித்ரா',
    'login': 'உள்நுழைவு',
    'register': 'பதிவு',
    'home': 'முகப்பு',
    'fullName': 'முழு பெயர்',
    'mobile': 'கைபேசி எண்',
    'captcha': 'கேப்சா',
    'captchaText': 'கேப்சா உரை',
    'sendOtp': 'OTP அனுப்பு',
    'registerCta': 'பதிவு செய்யவும்',
    'newUser': 'புதிய பயனர்? பதிவு',
    'alreadyRegistered': 'ஏற்கனவே பதிவுசெய்தீர்களா? உள்நுழைக',
    'enterOtp': 'OTP ஐ உள்ளிடவும்',
    'otpPlaceholder': '••••••',
    'enterPhone': 'நாட்டு குறியுடன் கைபேசி எண்ணை உள்ளிடவும்',
    'otpSentPrefix': 'OTP அனுப்பப்பட்டது',
    'captchaNotReady': 'கேப்சா தயார் இல்லை',
    'captchaEnter': 'கேப்சா உரை உள்ளிடவும்',
    'aboutUs': 'எங்களைப் பற்றி',
    'customerCare': 'வாடிக்கையாளர் பராமரிப்பு',
    'listProduct': 'தயாரிப்பை பட்டியலிடு',
    'marketplace': 'சந்தை',
    'recentListings': 'சமீபத்திய பட்டியல்கள்',
    'searchByCategory': 'வகையால் தேடு',
    'qualityCheck': 'தர சோதனை / தயாரிப்பு தரம் சோதனை',
    'searchSeeds': 'விதைகளைத் தேடு / சந்தை',
    'viewAll': 'அனைத்தையும் பார்க்க',
    'buyNow': 'இப்போது வாங்கவும்',
    'qty': 'அளவு',
    'processed': 'செயலாக்கப்பட்டது',
    'unknownFarmer': 'தெரியாத விவசாயி',
    'seedPriceMarket': 'விதை விலை சந்தை',
    'sellOilseed': 'எண்ணெய் வித்து விற்க',
    'seedMarket': 'விதை சந்தை',
    'byproductMarket': 'துணை தயாரிப்பு சந்தை',
    'byproductPriceMarket': 'துணை தயாரிப்பு விலை சந்தை',
    'buyOilseed': 'எண்ணெய் வித்து வாங்க',
    'myOrders': 'எனது ஆர்டர்கள்',
    'orderTracking': 'ஆர்டர் கண்காணிப்பு',
    'searchOilSeed': 'எண்ணெய் வித்து தேடுக',
    'searchPlaceholder': 'விதைகள், பயிர்களைத் தேடுங்கள்...',
    'recentPost': 'சமீபத்திய இடுகை',
    'menu': 'பட்டியல்',
    'usefulWebsites': 'பயனுள்ள இணையதளங்கள்',
    'pmKisan': 'பிஎம் கிசான் சம்மன் நிதி',
    'pmFasalBima': 'பிஎம் பயிர் காப்பீட்டுத் திட்டம்',
    'enam': 'e-NAM',
    'soilHealth': 'மண் சுகாதார அட்டை',
    'generateCertificate': 'சான்றிதழை உருவாக்கவும்',
    'krishiSenseTitle': 'கிருஷி சென்ஸ் : எண்ணெய் வித்து விலை முன்னறிவிப்பு AI',
    'hello': 'வணக்கம்',
    'trend': 'போக்கு',
    'rising': 'உயர்கிறது',
    'falling': 'வீழ்ச்சியடைகிறது',
    'sellNow': 'இப்போது விற்கவும்',
    'urgentAlertFallback':
        'அவசரம்: அடுத்த 48 மணி நேரத்தில் விதர்பா பகுதியில் கனமழை பெய்ய வாய்ப்புள்ளது. உங்கள் அறுவடை பயிர்களை பாதுகாக்கவும்.',
    'soyabean': 'சோயாபீன்',
    'mustard': 'கடுகு',
    'sesame': 'எள்',
    'sunflower': 'சூரியகாந்தி',
    'groundnut': 'நிலக்கடலை',
    'castor': 'ஆமணக்கு',
    'wheat': 'கோதுமை',
    'rice': 'அரிசி',
    'corn': 'சோளம்',
    'cotton': 'பருத்தி',
    'marketInsights': 'சந்தை நுண்ணறிவு',
    'bestSeasonalPick': 'சிறந்த பருவகால தேர்வு',
    'riskLevel': 'ஆபத்து நிலை',
    'high': 'உயர்',
    'medium': 'நடுத்தர',
    'low': 'குறைந்த',
    'expectedProfit': 'எதிர்பார்க்கப்படும் லாபம்',
    'recommendation': 'பரிந்துரை',
    'action': 'செயல்',
    'reason': 'காரணம்',
    'seasonalAnalysis': 'பருவகால பகுப்பாய்வு',
    'bestMonth': 'சிறந்த மாதம்',
    'worstMonth': 'மோசமான மாதம்',
    'opportunity': 'வாய்ப்பு',
    'hold': 'பிடித்து வைக்கவும்',
    'sell': 'விற்கவும்',
    'months': 'மாதங்கள்',
    'urgentAlerts': 'அவசர எச்சரிக்கைகள்',
    'january': 'ஜனவரி',
    'february': 'பிப்ரவரி',
    'march': 'மார்ச்',
    'april': 'ஏப்ரல்',
    'may': 'மே',
    'june': 'ஜூன்',
    'july': 'ஜூலை',
    'august': 'ஆகஸ்ட்',
    'september': 'செப்டம்பர்',
    'october': 'அக்டோபர்',
    'november': 'நவம்பர்',
    'december': 'டிசம்பர்',
    'now': 'இப்போது',
    '1m': '1மாதம்',
    '3m': '3மாதம்',
    '6m': '6மாதம்',
    'chatIntro':
        'வணக்கம்! நான் விவசாய நண்பன். நான் உங்களுக்கு எப்படி உதவ முடியும்?',
    'learn': 'கற்றுக்கொள்ளுங்கள்',
    'blogPosts': 'வலைப்பதிவு இடுகைகள்',
    'tutorialVideos': 'பயிற்சி வீடியோக்கள்',
    'watchNow': 'இப்போது பாருங்கள்',
    'readMore': 'மேலும் படிக்க',
  },
};
