# Generated by Django 5.2.8 on 2025-11-20 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('seeds', 'Seeds'), ('byproduct', 'Byproduct')], max_length=20)),
                ('product_name', models.CharField(max_length=100)),
                ('data_of_listing', models.DateField()),
                ('certificate', models.FileField(upload_to='certificates/')),
                ('amount_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_price_per_kg_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
