# Generated by Django 5.2.8 on 2025-11-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='data_of_listing',
            new_name='date_of_listing',
        ),
        migrations.RemoveField(
            model_name='product',
            name='certificate',
        ),
    ]
