# Generated by Django 5.2.8 on 2025-11-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=20)),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
