# Generated by Django 5.2.8 on 2025-11-22 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_inventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
