# Generated by Django 5.2.8 on 2025-12-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_product_location_product_quality_userprofile_state'),
    ]

    operations = [

        migrations.AddField(
            model_name='product',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
